version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy-notedly
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    image: registry.heroku.com/notedly/notedly-service:latest
    env_file:
      - ${ENV_FILE:-.env}
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: server-notedly
    ports:
      - '5005:5005'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: db-notedly
    ports:
      - '27017:27017'
    networks:
      - backend
  # db:
  #   image: postgresql:latest
  #   container_name: db-notedly
  #   environment:
  #     POSTGRESQL_USERNAME: root
  #     POSTGRESQL_PASSWORD: password
  #     POSTGRESQL_DATABASE: test
  #   ports:
  #     - '5432:5432'
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
